### ISSUE TITLE
Separate the generator from the sbt plugin

### ISSUE THREAD

**Issue by roti** [playframework/play-soap#288]
We would like to use play-soap with maven, and it would be possible if the generator (`PlayClientGenerator`, `PlaySEIGenerator` etc.) would be separated from the sbt-plugin, so that it can be used independently. I can prepare a pull request if you would be willing to make this change.

**Comment by ihostage** [comment]
Hi, @roti! 👋 
Yes, independence from the build system is one of the main tasks in my personal plan about Play SOAP 2.0 😄 
Just now the process migration PlayFramework to OpenCollective is underway and I wait for that because it can make sense for the name of the group of artifacts and packages.
But if you prepare a pull request it will be great and help me in the future  👍 Only I can't prognosis a release date 🤷‍♂️

**Comment by ihostage** [comment]
Fixes by #345
